workflows:
  emulator-test:
    name: Emulator test
    scripts:
      - |
        emulator @emulator -no-window -no-snapshot-save &
        adb wait-for-device
#      - ${ANDROID_HOME}/emulator/emulator -avd emulator -no-window -no-snapshot-save &
#       - adb wait-for-device
      - sleep 30
      - adb devices
