workflows:
  emulator-test:
    name: Emulator test
    scripts:
      - |
        ${ANDROID_HOME}/emulator/emulator -avd emulator -no-window -no-snapshot-save &
        adb wait-for-device
      - adb devices
